[phases.setup]
nixPkgs = ["glib", "nss", "atk", "cups", "dbus", "gtk3", "pango", "alsa-lib", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libXcursor", "xorg.libXi", "xorg.libXtst", "libdrm", "libgbm"]
